vim.opt.undodir = os.getenv("HOME") .. "/.nvim/undodir"
vim.opt.undofile = true
vim.opt.undolevels = 10000
vim.opt.backup = false
vim.opt.swapfile = false
vim.opt.number = true              --  line numbers
vim.opt.hlsearch = true            -- highlight search
vim.opt.incsearch = true           -- show search matches while typing
vim.opt.ignorecase = true          -- case unsensitive search
vim.opt.tabstop = 2                -- tab width
vim.opt.shiftwidth = 2             -- tabs
vim.opt.softtabstop = 2            -- tabs
vim.opt.shiftround = true          -- when at 3 spaces, and I hit > ... go to 4, not 5
vim.opt.expandtab = true           -- don't use real tabs
vim.opt.smartindent = true         -- advanced indent
vim.opt.updatetime = 80
vim.opt.list = true                -- show hidden chars
vim.opt.listchars = "tab:^T,eol:¬" -- hidden chars representation
vim.opt.showmatch = true           -- show matching elements
vim.opt.clipboard = "unnamedplus"  -- advanced clipboard"
vim.opt.smartcase = true           -- if there are caps, go case-sensitive
vim.opt.scrolloff = 3              -- lines before EOF
vim.opt.switchbuf = "usetab"
vim.opt.timeoutlen = 400           -- Time in milliseconds to wait for a mapped sequence to complete.
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
vim.opt.foldtext = ""
vim.opt.foldlevelstart = 5
